version: "3"

services:
  postgres:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

networks:
  stack: {}
