databases:
  - name: communion-lineup
    databaseName: communion_lineup_production
    user: communion

services:
  - type: web
    name: communion-lineup
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: communion_lineup_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false